# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DdevEdge < Formula
  desc "DDEV"
  homepage "https://github.com/ddev-test/ddev"
  version "1.23.64"
  license "Apache 2"

  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddev-test/ddev/releases/download/v1.23.64/ddev_macos-amd64.v1.23.64.tar.gz"
      sha256 "17d296240539ac1e4e7dff52bad962992726145ea5cac0d6e03ccc3ec0986f1a"

      def install
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev_hostname", "#{bin}/ddev_hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev_hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddev-test/ddev/releases/download/v1.23.64/ddev_macos-arm64.v1.23.64.tar.gz"
      sha256 "11be7d2910d8d01590d28d6936b7d579432d12bee98c3e4370b50eae365e3880"

      def install
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev_hostname", "#{bin}/ddev_hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev_hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ddev-test/ddev/releases/download/v1.23.64/ddev_linux-amd64.v1.23.64.tar.gz"
      sha256 "7a45c7ec9ce995d758bf2072938eaaff176333f0651f6ac560e653494954bdbf"
      def install
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev_hostname", "#{bin}/ddev_hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev_hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ddev-test/ddev/releases/download/v1.23.64/ddev_linux-arm64.v1.23.64.tar.gz"
      sha256 "f424bb3a2bf282f450791502067cd9b9bde65c839a5367847e9ce68433d381b9"
      def install
        if build.head?
            system "sh", "-c", "git fetch --unshallow >/dev/null 2>&1" if File.exist?("#{HOMEBREW_REPOSITORY}/.git/shallow")
            system "sh", "-c", "git fetch --tags -f >/dev/null 2>&1"
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "build", "completions"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev_hostname", "#{bin}/ddev_hostname"
            bash_completion.install ".gotmp/bin/completions/ddev_bash_completion.sh" => "ddev"
            zsh_completion.install ".gotmp/bin/completions/ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install ".gotmp/bin/completions/ddev_fish_completion.sh" => "ddev.fish"
        else
            bin.install "ddev"
            bin.install "ddev_hostname"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "_ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev.fish"
        end
      end
    end
  end

  head do
    url "https://github.com/ddev-test/ddev.git", branch: "main"
    depends_on "go" => :build
    depends_on "make" => :build
  end
  # fail fast if tapped under the old drud or rfay names
  def initialize(*args, **kwargs)
    super(*args, **kwargs)
    if ["drud/homebrew-ddev", "drud/homebrew-ddev-edge", "ddev-test/homebrew-ddev-edge", "rfay/homebrew-ddev-edge"].include?(tap&.full_name)
      odie <<~EOS
        ERROR: your homebrew tap is the ancient #{tap.full_name},
        but that repository has moved.
        Please run:
          rm -rf "$(brew --repo #{tap.full_name})"
          brew uninstall -f ddev ddev-edge
          brew install ddev/ddev-edge/ddev-edge
      EOS
    end
  end

  test do
    system "#{bin}/ddev --version"
  end
end
